name: cloud-cicd-infrastructure
description: AWS infrastructure for full-stack CI/CD project
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
